export const quotes = {
  morning: [
    "Wake up and chase your dreams 💪",
    "Aaj ka din tumhara hai, aage badho 🚀",
    "Discipline today, success tomorrow ⚡",
    "Subah uthkar apne goals yaad karo 🔥",
    "Dream big, start small, act now",
    "Aaj kuch naya karne ka perfect din hai",
    "Success shuru hoti hai ek strong morning se",
    "Sapno ko sach karne ka waqt aa gaya hai",
    "Don’t waste your morning, it defines your day",
    "Aaj mehnat karo, kal celebrate karoge",
    "Rise early, focus deeply, win daily",
    "Har subah ek nayi opportunity hoti hai",
    "Push yourself, no one else will do it for you",
    "Aaj discipline rakho, kal freedom milegi",
    "Start your day with purpose and energy ⚡",
    "Khud par bharosa rakho, sab possible hai",
    "Make today count, no excuses",
    "Aaj ka effort tumhe alag banayega",
    "Consistency is the real power 💯",
    "Jeet unhi ki hoti hai jo rukte nahi",
  ],

  noon: [
    "Keep going, you’re doing better than you think 👍",
    "Thoda aur mehnat karo, manzil paas hai",
    "Stay focused, don’t lose momentum 🎯",
    "Ruko mat, abhi bahut kuch baaki hai",
    "Half day ho gaya, ab double energy lagao ⚡",
    "Tum sahi direction me ho, bas continue karo",
    "Hard work ka result milta hi hai",
    "Don’t slow down now, keep pushing",
    "Aaj ka kaam aaj hi finish karo",
    "Focus karo, distractions ignore karo",
    "Momentum mat lose karo, ye important time hai",
    "Thak gaye ho? Thoda aur push karo 💪",
    "Winners kabhi beech me nahi rukte",
    "Aaj ka din strong finish karo",
    "Chhoti progress bhi progress hoti hai",
    "Keep moving forward, no matter what",
    "Abhi ruk gaye toh piche reh jaoge",
    "Believe in your process 🔥",
    "Consistency se hi success aata hai",
    "Tum kar sakte ho, bas lage raho",
  ],

  evening: [
    "You did well today, be proud 🌙",
    "Aaj ka effort kal ki jeet banega",
    "Rest, recharge, and rise again ⚡",
    "Aaj jo kiya woh progress hai, perfect nahi hona zaroori",
    "Kal ek aur chance milega, ready rehna",
    "Reflect karo, improve karo, repeat karo",
    "Aaj ka din respect karo, tumne try kiya",
    "Har din perfect nahi hota, par growth hoti hai",
    "Kal aur better karoge, trust yourself",
    "Don’t stress, you’re improving daily",
    "Aaj thoda kam hua? Kal zyada kar lena",
    "Sleep with peace, tomorrow is yours 🌙",
    "Mistakes are part of success journey",
    "Aaj ka lesson kal ka power banega",
    "Be proud, you didn’t quit today",
    "Relax karo, recharge ho jao",
    "Aaj ke effort ko underestimate mat karo",
    "Kal ek fresh start milega 🔥",
    "Consistency maintain karo, result aayega",
    "You’re growing, keep believing",
  ],
};